### ISSUE TITLE
QS dependency is out of date

### ISSUE THREAD

**Issue by timrnz** [rackt/history#161]
Currently, the dependency is: `"qs": "^4.0.0"`.

Building react-router / redux-router apps with this dependency breaks until I delete the node_module of this package, then install `"qs": "^6.0.0"` myself as a dependency of my own app.

Ideally I shouldn't have to do this.

**Comment by taion** [comment]
How? It's a direct dependency rather than a peer dependency. npm manages this for you. In fact qs 6.x has no browser support. You're doing something weird.

**Comment by timrnz** [comment]
I'm using webpack for my build, and this package is installed via NPM, not via bower, here is the error I get when I use the current version.

It is related to this : https://github.com/hapijs/qs/issues/128

```
ERROR in qs (bower component)
Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/qs.js in /.../node_modules/history/node_modules/qs
 @ qs (bower component) 1:17-40
```

Since the current version of QS#6.0.x, the code that drops with the installed package includes the dist folder, the code works as expected. As of QS#4.0.0, the dist folder and corresponding qs.js file don't exist at all.

**Comment by taion** [comment]
You need to explicitly install the dependencies you use - npm manages dependencies hierarchically, so the fact that `history` depends on `qs` doesn't let you access anything from `qs` from your own code unless you separately install `qs` yourself.

That said, it's also an error condition to:
1. Use `dist/qs.js` with webpack/npm, since that's the UMD bundle, and you should be pulling in the actual source
2. Use `dist/qs.js` on qs 6.x, because it's actually outdated (the distributed bundle there is actually still qs 5.2.0 due to some packaging errors on the part of the maintainers)
3. Use qs 6.x in browser at all, because they've effectively dropped browser support with 6.x

I suggest further familiarizing yourself with how npm and webpack work.

**Comment by timrnz** [comment]
I think the problem is, not that I'm trying to use QS at all, rather than the fact that if I install the history module over NPM, it fails any sort of builds due to the fact the required file is missing from the QS#4.x package.

Have a go, it works when you take my approach.

Can you please re-open as this is still an issue.

**Comment by taion** [comment]
It's not a packaging issue on our end - we have many users using webpack + npm and it's working fine. I think you've possibly misconfigured something with webpack. Try reaching out on either Reactiflux or Stack Overflow for help with webpack configuration; we'd be happy to help you there. The issue tracker however is not really appropriate as a support forum.

**Comment by timrnz** [comment]
Just did some searching, I'm not the only one having this problem.

http://stackoverflow.com/questions/33500823/module-not-found-error-cannot-resolve-file-or-directory-dist-qs-js

It could be the bowerWebPack plugin I'm using. I'll investigate more and report back.

**Comment by taion** [comment]
If you're using a webpack plugin that is trying to treat npm packages as Bower packages, you are likely to hit issues if you're mixing stuff across npm and Bower, yes.
