### ISSUE TITLE
Router.History.back() goes back in browser history, not app history

### ISSUE THREAD

**Issue by mlunoe** [rackt/history#195]
We have an iframe within the page, that contains a close button, that will trigger a Router.History.back().
Because it is possible to navigate within the iframe, it will add to the browser history, but not change the path. Calling Router.History.back() will therefore go back in browser history (including iframe history), in stead of only the history captured by our app.
I would expect Router.History.back() to only navigate the history of the app, but it does this:
https://github.com/rackt/react-router/blob/0.13.x/modules/History.js#L26

Created a fiddle with the problem still existing in React Router v1.0.0-rc1 (latest one I could find available in cdn) and React v0.14.0: https://jsfiddle.net/mlunoe/kwg1da3a/1/

Reference issue: https://github.com/rackt/react-router/issues/1874

**Comment by taion** [comment]
Use `createMemoryHistory` if you don't want to tie into the actual browser history API.

**Comment by mlunoe** [comment]
Here is a link for the interested readers: https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#creatememoryhistory

**Comment by mlunoe** [comment]
I have updated the fiddle to show that the problem still exists using `createMemoryHistory`. Please take a look at the example I have created for you.

**Comment by taurose** [comment]
So you want to embed an arbitrary iframe that comes with its own navigation (via normal links or whatever) but have `history.back()` etc. ignore the iframe's history?

I could be wrong, but I don't think that's possible for us to handle since it's all managed by the browser. If you have control over the iframe's content, you should try to make sure that it's not creating new history entries to begin with (e.g. by using `createMemoryHistory`). Or you could try workarounds like capturing all link clicks and make them use `location.replace(..)` instead of the default behavior.

**Comment by mlunoe** [comment]
Ok, that's fair. I guess I focused on the solution, rather than actually solving the problem.
I have updated the fiddle to show the solution: https://jsfiddle.net/mlunoe/kwg1da3a/

It includes an iframe and you can navigate within the iframe, but still be able to use the `goBack` function from history to go back in the react router history.

Thanks for the help!
