### ISSUE TITLE
Use hash path as queryKey when queryKey is disabled?

### ISSUE THREAD

**Issue by taion** [rackt/history#72]
Would it make sense to use the path as an implicit `queryKey` when `queryKey` is disabled? It's not as good as having an actual query key, but might be an improvement in common use cases.

**Comment by mjackson** [comment]
That makes sense only insofar as your URLs are unique to the extra state you provide (i.e. the `state` argument to `pushState`). Otherwise you risk unintentionally overwriting state from the last time the user visited a certain URL. To avoid this ambiguity (and to save some poor developer having to troubleshoot this for hours in the future) I'd rather not use the URL as a `location.key`.

Also, just a quick note about disabling `queryKey`: don't do it. Everyone has been asking about it, but the default is there so your stuff doesn't break.

**Comment by taion** [comment]
Fair enough. I guess this isn't safe as a default. Do you think it's worth offering as a non-default option? I'm asking here because it doesn't seem like there's a straightforward way to e.g. extend `createHashHistory` in my own code to enable this pattern.
