### ISSUE TITLE
Location key

### ISSUE THREAD

**Issue by brenoc** [rackt/history#76]
I think I'm not getting my head around the property "key" of the "location" object. In the docs it says: "A unique identifier for this location". 

But I have the following scenario:

1. The user opens the route `/home`
2. History sets location object with the key: "92olpy"
3. The user go to `/about`
4. History sets location object with the key: "vkioqa"
5. The user goes back to `/home`
6. History sets location object with the key: **"uipj9o"**

Why History gives a different key for the same location?

**Comment by mjackson** [comment]
> The user goes back to `/home`

It all depends on *how* the user "goes back". If the operation is a `PUSH` (i.e. they clicked on a link to get back to `/home`) then you should get a new key because you'll have 3 items in the history stack, and you're on the last one. i.e. the history stack looks like this:

1. `/home` with key `92olpy`
2. `/about` with key `vkioqa`
3. `/home` with key `uipj9o` <- the user is here

However, if the user gets back to `/home` by **clicking the back button**, the history stack will look like this:

1. `/home` with key `92olpy` <- the user is here
2. `/about` with key `vkioqa`

So `location.key` refers to a specific spot on the history stack, not a URL.

**Comment by brenoc** [comment]
@mjackson thanks for the great explanation
